import type { Time } from "lightweight-charts";

export type Candle={time:number;open:number;high:number;low:number;close:number;volume?:number};
export type EntryConfig={enabled:boolean;tf:string;showMarkers:boolean;fastSma:number;slowSma:number;atrLen:number;rsiLen:number;macdFast:number;macdSlow:number;macdSignal:number;expansionMomentum:number;expansionEnergy:number;expansionVolatility:number;expansionCompressionMax:number;compressionMin:number;phaseSwitchMargin:number};
export type ExitConfig={enabled:boolean;tf:string;showMarkers:boolean;showLines:boolean;fastSma:number;slowSma:number;atrLen:number;rsiLen:number;macdFast:number;macdSlow:number;macdSignal:number;offset:number;useSlowExit:boolean;exitOnTrendFlip:boolean};
export type ChannelConfig={enabled:boolean;tf:string;showLines:boolean;atrPeriod:number;multiplier:number;useRmaAtr:boolean};
export type ControllerConfig={enabled:boolean;showMarkers:boolean;requireTrend:boolean;allowFlip:boolean};
export type EntryRow={time:number;dir:number;regime:number;phase:number;trend:number;momentum:number;energy:number;volatility:number;compression:number;exhaustion:number;pullback:number;atr:number|null;rsi:number|null;macd:number|null;signal:number|null;hist:number|null;entry:"LONG"|"SHORT"|"NONE"};
export type ExitRow={time:number;exit:"LONG"|"SHORT";reason:"EXIT_LAB"};
export type ChannelRow={time:number;trend:1|-1;value:number};
export type ControllerState="FLAT"|"LONG"|"SHORT";
export type ControllerRow={time:number;action:"OPEN_LONG"|"OPEN_SHORT"|"EXIT_LONG"|"EXIT_SHORT"|"FLIP_LONG"|"FLIP_SHORT";state:ControllerState;reason:"ENTRY"|"EXIT_LAB_EXIT"|"OPPOSITE_ENTRY"};
export type BacktestStats={trades:number;wins:number;losses:number;grossProfit:number;grossLoss:number;net:number;profitFactor:number|null;winRate:number};

export const DEFAULT_ENTRY:EntryConfig={enabled:true,tf:"5m",showMarkers:true,fastSma:20,slowSma:50,atrLen:14,rsiLen:14,macdFast:2,macdSlow:26,macdSignal:9,expansionMomentum:65,expansionEnergy:45,expansionVolatility:55,expansionCompressionMax:60,compressionMin:62,phaseSwitchMargin:8};
export const DEFAULT_EXIT:ExitConfig={enabled:true,tf:"MTF",showMarkers:true,showLines:true,fastSma:20,slowSma:50,atrLen:14,rsiLen:14,macdFast:2,macdSlow:26,macdSignal:9,offset:0,useSlowExit:true,exitOnTrendFlip:false};
export const DEFAULT_CHANNEL:ChannelConfig={enabled:true,tf:"30m",showLines:true,atrPeriod:10,multiplier:3,useRmaAtr:true};
export const DEFAULT_CONTROLLER:ControllerConfig={enabled:true,showMarkers:true,requireTrend:true,allowFlip:true};

export function tfSeconds(tf:string){const raw=tf.trim().toLowerCase();if(raw==="mtf")return 60;if(raw.endsWith("h"))return Math.max(1,Number(raw.slice(0,-1)||1))*3600;return Math.max(1,Number(raw.replace("m",""))||1)*60;}
export function resample(candles:Candle[],tf:string):Candle[]{if(!candles.length)return[];const sec=tfSeconds(tf),buckets=new Map<number,Candle>();for(const c of candles){const t=Math.floor(c.time/sec)*sec,row=buckets.get(t);if(!row)buckets.set(t,{time:t,open:c.open,high:c.high,low:c.low,close:c.close,volume:c.volume||0});else{row.high=Math.max(row.high,c.high);row.low=Math.min(row.low,c.low);row.close=c.close;row.volume=(row.volume||0)+(c.volume||0);}}return[...buckets.values()].sort((a,b)=>a.time-b.time);}
function sma(values:number[],len:number):(number|null)[]{const out:(number|null)[]=Array(values.length).fill(null);let sum=0;for(let i=0;i<values.length;i++){sum+=values[i];if(i>=len)sum-=values[i-len];if(i>=len-1)out[i]=sum/len;}return out;}
function ema(values:(number|null)[],len:number):(number|null)[]{const out:(number|null)[]=Array(values.length).fill(null),a=2/(len+1);let prev:number|null=null;for(let i=0;i<values.length;i++){const v=values[i];if(v==null)continue;prev=prev==null?v:a*v+(1-a)*prev;out[i]=prev;}return out;}
function rma(values:(number|null)[],len:number):(number|null)[]{const out:(number|null)[]=Array(values.length).fill(null),seed:number[]=[];let prev:number|null=null;for(let i=0;i<values.length;i++){const v=values[i];if(v==null)continue;if(prev==null){seed.push(v);if(seed.length===len){prev=seed.reduce((a,b)=>a+b,0)/len;out[i]=prev;}}else{prev=(prev*(len-1)+v)/len;out[i]=prev;}}return out;}
function stdev(values:number[],len:number):(number|null)[]{const out:(number|null)[]=Array(values.length).fill(null);for(let i=len-1;i<values.length;i++){const s=values.slice(i-len+1,i+1),m=s.reduce((a,b)=>a+b,0)/len;out[i]=Math.sqrt(s.reduce((a,b)=>a+(b-m)*(b-m),0)/len);}return out;}
function clamp(x:number){return Math.max(0,Math.min(100,x));}
function scoreAbs(x:number,scale:number){return scale!==0?clamp(Math.abs(x)/scale*100):0;}

function calculateQtrendState(candles:Candle[],cfg:Pick<EntryConfig,"fastSma"|"slowSma"|"atrLen"|"rsiLen"|"macdFast"|"macdSlow"|"macdSignal"|"expansionMomentum"|"expansionEnergy"|"expansionVolatility"|"expansionCompressionMax"|"compressionMin"|"phaseSwitchMargin">):EntryRow[]{
 const n=candles.length,close=candles.map(c=>c.close),open=candles.map(c=>c.open),high=candles.map(c=>c.high),low=candles.map(c=>c.low),smaFast=sma(close,cfg.fastSma),smaSlow=sma(close,cfg.slowSma);
 const tr:(number|null)[]=close.map((_,i)=>i===0?high[i]-low[i]:Math.max(high[i]-low[i],Math.abs(high[i]-close[i-1]),Math.abs(low[i]-close[i-1]))),atr=rma(tr,cfg.atrLen),atrAvg=sma(atr.map(v=>v??0),50),gains:(number|null)[]=Array(n).fill(null),losses:(number|null)[]=Array(n).fill(null);
 for(let i=1;i<n;i++){const d=close[i]-close[i-1];gains[i]=Math.max(d,0);losses[i]=Math.max(-d,0);}const avgGain=rma(gains,cfg.rsiLen),avgLoss=rma(losses,cfg.rsiLen),rsi:(number|null)[]=close.map((_,i)=>avgGain[i]==null||avgLoss[i]==null?null:avgLoss[i]===0?100:100-(100/(1+(avgGain[i] as number)/(avgLoss[i] as number))));
 const eFast=ema(close,cfg.macdFast),eSlow=ema(close,cfg.macdSlow),macd:(number|null)[]=close.map((_,i)=>eFast[i]==null||eSlow[i]==null?null:(eFast[i] as number)-(eSlow[i] as number)),sig=ema(macd,cfg.macdSignal),hist=macd.map((v,i)=>v==null||sig[i]==null?null:v-(sig[i] as number)),sd=stdev(close,20),sdAvg=sma(sd.map(v=>v??0),50);
 const rows:EntryRow[]=[];let trendAge=0,phase=4,prevDir=0,prevMomentum=0,prevEnergy=0,prevVol=0,prevFlow=0;
 for(let i=0;i<n;i++){
  const sf=smaFast[i],ss=smaSlow[i],a=atr[i],aa=atrAvg[i],rv=rsi[i],m=macd[i],sg=sig[i],h=hist[i],sdv=sd[i],sda=sdAvg[i];
  if(i<Math.max(cfg.slowSma+12,60)||sf==null||ss==null||a==null||aa==null||rv==null||m==null||sg==null||h==null||sdv==null||sda==null){rows.push({time:candles[i].time,dir:0,regime:0,phase:4,trend:0,momentum:0,energy:0,volatility:0,compression:0,exhaustion:0,pullback:0,atr:a??null,rsi:rv??null,macd:m??null,signal:sg??null,hist:h??null,entry:"NONE"});continue;}
  const rsiSpeed=i>=3&&rsi[i-3]!=null?rv-(rsi[i-3] as number):0,rsiAccel=i>=6&&rsi[i-3]!=null&&rsi[i-6]!=null?rsiSpeed-((rsi[i-3] as number)-(rsi[i-6] as number)):0,histSpeed=i>=3&&hist[i-3]!=null?h-(hist[i-3] as number):0,body=Math.abs(close[i]-open[i]),range=high[i]-low[i],bodyPct=range>0?body/range:0,wickPct=range>0?1-bodyPct:0,slopeSlow=i>=5&&smaSlow[i-5]!=null?ss-(smaSlow[i-5] as number):0,prevSlopeSlow=i>=10&&smaSlow[i-5]!=null&&smaSlow[i-10]!=null?(smaSlow[i-5] as number)-(smaSlow[i-10] as number):0,curveSlow=slopeSlow-prevSlopeSlow;
  const trendSlope=scoreAbs(slopeSlow,a*.6),trendCurve=scoreAbs(curveSlow,a*.4),priceDist=scoreAbs(close[i]-ss,a*2),maAlign=sf!==ss?100:0,trend=clamp(trendSlope*.35+trendCurve*.20+priceDist*.25+maAlign*.20),rsiPower=scoreAbs(rv-50,25),rsiSpeedScore=scoreAbs(rsiSpeed,10),rsiAccelScore=scoreAbs(rsiAccel,8),macdPower=scoreAbs(h,a*.08),macdSpeedScore=scoreAbs(histSpeed,a*.05),momentum=clamp(rsiPower*.20+rsiSpeedScore*.20+rsiAccelScore*.15+macdPower*.25+macdSpeedScore*.20);
  const atrEnergy=aa>0?clamp(a/aa*65):0,rangeEnergy=a>0?clamp(range/a*55):0,bodyEnergy=clamp(bodyPct*100),impulse=i>=5?Math.abs(close[i]-close[i-5]):0,impulseEnergy=a>0?clamp(impulse/a*30):0,energy=clamp((atrEnergy+rangeEnergy+bodyEnergy+impulseEnergy)/4),atrVol=aa>0?clamp(a/aa*100):0,stdevVol=sda>0?clamp(sdv/sda*100):0,rangeVol=a>0?clamp(range/a*70):0,volatility=clamp(atrVol*.45+stdevVol*.35+rangeVol*.20);
  const smallBody=clamp((1-bodyPct)*100),highWicks=clamp(wickPct*100),lowAtr=aa>0?clamp((1.35-a/aa)*100):0,flatSma=clamp(100-trendSlope),tightRange=a>0?clamp((1.2-range/a)*100):0,compression=clamp(smallBody*.20+highWicks*.20+lowAtr*.25+flatSma*.20+tightRange*.15),bull=(close[i]>sf?20:0)+(close[i]>ss?20:0)+(sf>ss?20:0)+(i>=5&&smaSlow[i-5]!=null&&ss>(smaSlow[i-5] as number)?20:0)+(i>=5&&close[i]>close[i-5]?20:0),bear=(close[i]<sf?20:0)+(close[i]<ss?20:0)+(sf<ss?20:0)+(i>=5&&smaSlow[i-5]!=null&&ss<(smaSlow[i-5] as number)?20:0)+(i>=5&&close[i]<close[i-5]?20:0),structure=Math.max(bull,bear),dir=bull>bear?1:bear>bull?-1:0;
  trendAge=dir!==0&&dir===prevDir?trendAge+1:dir!==0?1:0;const trendAgeScore=clamp(trendAge/80*100),balance=clamp(compression*.45+(100-trend)*.20+(100-energy)*.20+(100-volatility)*.15),momentumFalling=momentum<prevMomentum,energyFalling=energy<prevEnergy,volFalling=volatility<prevVol,momentumRising=momentum>prevMomentum,energyRising=energy>prevEnergy,pullback=clamp(compression*.30+(100-energy)*.25+trendAgeScore*.15+(momentumFalling?20:0)+(energyFalling?10:0)),exhaustion=clamp(trendAgeScore*.30+pullback*.30+(momentumFalling?20:0)+(energyFalling?15:0)+(volFalling?10:0)),trendReg=clamp(trend*.35+structure*.35+trendAgeScore*.15+(100-balance)*.15),rangeReg=clamp(compression*.40+balance*.35+(100-trend)*.15+(100-energy)*.10),regime=trendReg>=rangeReg?1:0;
  const isCompression=compression>=cfg.compressionMin&&energy<=45&&balance>=50,isExpansion=momentum>=cfg.expansionMomentum&&energy>=cfg.expansionEnergy&&volatility>=cfg.expansionVolatility&&compression<=cfg.expansionCompressionMax,isPullback=regime===1&&trend>=55&&structure>=60&&trendAgeScore>=20&&(energy<=45||momentumFalling||energyFalling),isExhaustion=regime===1&&exhaustion>=65&&trendAgeScore>=25&&pullback>=55,compressionPower=clamp((compression+balance+(100-energy))/3),expansionPower=clamp((momentum+energy+volatility+trend)/4),pullbackPower=clamp((pullback+trend+structure+trendAgeScore)/4),exhaustionPower=exhaustion,prevPhase=phase,currentPower=phase===1?expansionPower:phase===2?pullbackPower:phase===3?exhaustionPower:compressionPower;let candidate=phase,candidatePower=currentPower;
  if(regime===0){if(isExpansion&&compression<55){candidate=1;candidatePower=expansionPower;}else{candidate=4;candidatePower=compressionPower;}}else if(phase===4){if(isExpansion){candidate=1;candidatePower=expansionPower;}}else if(phase===1){if(isExhaustion){candidate=3;candidatePower=exhaustionPower;}else if(isPullback){candidate=2;candidatePower=pullbackPower;}}else if(phase===2){if(isExhaustion){candidate=3;candidatePower=exhaustionPower;}else if(isExpansion&&energyRising){candidate=1;candidatePower=expansionPower;}}else if(phase===3){if(isCompression){candidate=4;candidatePower=compressionPower;}else if(isExpansion&&energyRising&&momentumRising){candidate=1;candidatePower=expansionPower;}}
  const directionChanged=dir!==0&&dir!==prevDir;if(candidate!==phase&&(directionChanged||candidatePower>=currentPower+cfg.phaseSwitchMargin))phase=candidate;const dna=regime===1&&phase===1?dir:0;let flow=dna;if(prevPhase===4&&phase===1)flow=0;else if(prevPhase===1&&phase===2)flow=0;else if(prevPhase===2&&phase===1)flow=dir;else if(prevPhase===1&&phase===3)flow=0;else if(prevPhase===3&&phase===4)flow=0;const longEdge=flow===1&&prevFlow!==1,shortEdge=flow===-1&&prevFlow!==-1,entry:EntryRow["entry"]=longEdge&&close[i]>open[i]?"LONG":shortEdge&&close[i]<open[i]?"SHORT":"NONE";
  rows.push({time:candles[i].time,dir,regime,phase,trend,momentum,energy,volatility,compression,exhaustion,pullback,atr:a,rsi:rv,macd:m,signal:sg,hist:h,entry});prevDir=dir;prevMomentum=momentum;prevEnergy=energy;prevVol=volatility;prevFlow=flow;
 }
 return rows;
}
export function calculateEntry(candles:Candle[],cfg:EntryConfig){return calculateQtrendState(candles,cfg);}

function exitStateConfig(cfg:ExitConfig):EntryConfig{return{enabled:true,tf:"5m",showMarkers:false,fastSma:cfg.fastSma,slowSma:cfg.slowSma,atrLen:cfg.atrLen,rsiLen:cfg.rsiLen,macdFast:cfg.macdFast,macdSlow:cfg.macdSlow,macdSignal:cfg.macdSignal,expansionMomentum:65,expansionEnergy:45,expansionVolatility:55,expansionCompressionMax:60,compressionMin:62,phaseSwitchMargin:8};}
function completedStates(base:Candle[],tf:string,cfg:ExitConfig){const sec=tfSeconds(tf),knownThrough=(base[base.length-1]?.time??0)+60,candles=resample(base,tf).filter(c=>c.time+sec<=knownThrough),states=calculateQtrendState(candles,exitStateConfig(cfg));return states.map(r=>({...r,availableAt:r.time+sec}));}
export function calculateExitCausal(base:Candle[],cfg:ExitConfig):ExitRow[]{if(!cfg.enabled||!base.length)return[];const s5=completedStates(base,"5m",cfg),s15=completedStates(base,"15m",cfg),s30=completedStates(base,"30m",cfg),s60=completedStates(base,"1h",cfg),rows:ExitRow[]=[];let i5=-1,i15=-1,i30=-1,i60=-1,prevLong=false,prevShort=false;for(const c of base){const t=c.time+60;while(i5+1<s5.length&&s5[i5+1].availableAt<=t)i5++;while(i15+1<s15.length&&s15[i15+1].availableAt<=t)i15++;while(i30+1<s30.length&&s30[i30+1].availableAt<=t)i30++;while(i60+1<s60.length&&s60[i60+1].availableAt<=t)i60++;if(i5<0||i15<0||i30<0||i60<0)continue;const a=s5[i5],b=s15[i15],c30=s30[i30],c60=s60[i60];const longExit=a.dir===-1&&b.dir===-1&&((c30.dir===1&&c30.phase===3)||(c60.dir===1&&c60.phase===3));const shortExit=a.dir===1&&b.dir===1&&((c30.dir===-1&&c30.phase===3)||(c60.dir===-1&&c60.phase===3));if(longExit&&!prevLong)rows.push({time:t,exit:"LONG",reason:"EXIT_LAB"});if(shortExit&&!prevShort)rows.push({time:t,exit:"SHORT",reason:"EXIT_LAB"});prevLong=longExit;prevShort=shortExit;}return rows;}
function lastSma(values:number[],len:number){if(len<=0||values.length<len)return null;let sum=0;for(let i=values.length-len;i<values.length;i++)sum+=values[i];return sum/len;}
export function calculateExitLinesVisual(base:Candle[],cfg:ExitConfig,chartTf:string){const candles=resample(base,chartTf),closes=candles.map(c=>c.close),slow:{time:Time;value:number}[]=[];for(let i=0;i<candles.length;i++){const v=lastSma(closes.slice(0,i+1),cfg.slowSma);if(v!=null)slow.push({time:candles[i].time as Time,value:v});}return{fast:[] as {time:Time;value:number}[],slow,upper:[] as {time:Time;value:number}[],lower:[] as {time:Time;value:number}[]};}

function completedModuleCandles(base:Candle[],tf:string){if(!base.length)return[];const moduleSeconds=tfSeconds(tf),knownThrough=base[base.length-1].time+60;return resample(base,tf).filter(c=>c.time+moduleSeconds<=knownThrough);}
function availableChartTime(moduleStart:number,moduleTf:string,chartTf:string){const availableAt=moduleStart+tfSeconds(moduleTf),chartSeconds=tfSeconds(chartTf);return Math.floor((availableAt-1)/chartSeconds)*chartSeconds;}
export function calculateSupertrendVisual(base:Candle[],cfg:ChannelConfig,chartTf:string):{time:Time;value:number;color:string}[]{const candles=completedModuleCandles(base,cfg.tf),trs:number[]=[],output:{time:Time;value:number;color:string}[]=[];let atr:number|null=null,trend:1|-1=1,previousUp:number|null=null,previousDn:number|null=null;for(let i=0;i<candles.length;i++){const candle=candles[i],previous=i>0?candles[i-1]:null,tr=previous==null?candle.high-candle.low:Math.max(candle.high-candle.low,Math.abs(candle.high-previous.close),Math.abs(candle.low-previous.close));trs.push(tr);if(cfg.useRmaAtr){if(atr!=null)atr=(atr*(cfg.atrPeriod-1)+tr)/cfg.atrPeriod;else if(trs.length>=cfg.atrPeriod)atr=trs.slice(-cfg.atrPeriod).reduce((a,b)=>a+b,0)/cfg.atrPeriod;}else if(trs.length>=cfg.atrPeriod)atr=trs.slice(-cfg.atrPeriod).reduce((a,b)=>a+b,0)/cfg.atrPeriod;if(atr==null)continue;const src=(candle.high+candle.low)/2,basicUp=src-cfg.multiplier*atr,basicDn=src+cfg.multiplier*atr,up:number=previousUp!=null&&previous!=null&&previous.close>previousUp?Math.max(basicUp,previousUp):basicUp,dn:number=previousDn!=null&&previous!=null&&previous.close<previousDn?Math.min(basicDn,previousDn):basicDn;if(trend===-1&&previousDn!=null&&candle.close>previousDn)trend=1;else if(trend===1&&previousUp!=null&&candle.close<previousUp)trend=-1;previousUp=up;previousDn=dn;output.push({time:availableChartTime(candle.time,cfg.tf,chartTf) as Time,value:trend===1?up:dn,color:trend===1?"#22c55e":"#ef4444"});}return output;}
export function calculateSupertrendCausal(base:Candle[],cfg:ChannelConfig):ChannelRow[]{const bucketSeconds=tfSeconds(cfg.tf),completedTrs:number[]=[],rows:ChannelRow[]=[];let bucket:number|null=null,partial:Candle|null=null,previousBar:Candle|null=null,committedAtr:number|null=null,committedTrend:1|-1=1,committedUp:number|null=null,committedDn:number|null=null;const trueRange=(bar:Candle,previous:Candle|null)=>previous==null?bar.high-bar.low:Math.max(bar.high-bar.low,Math.abs(bar.high-previous.close),Math.abs(bar.low-previous.close));const provisionalAtr=(tr:number)=>{if(cfg.useRmaAtr){if(committedAtr!=null)return(committedAtr*(cfg.atrPeriod-1)+tr)/cfg.atrPeriod;const seed=[...completedTrs,tr];return seed.length>=cfg.atrPeriod?seed.slice(-cfg.atrPeriod).reduce((a,b)=>a+b,0)/cfg.atrPeriod:null;}const window=[...completedTrs,tr];return window.length>=cfg.atrPeriod?window.slice(-cfg.atrPeriod).reduce((a,b)=>a+b,0)/cfg.atrPeriod:null;};const candidate=(bar:Candle)=>{const tr=trueRange(bar,previousBar),atr=provisionalAtr(tr);if(atr==null)return null;const src=(bar.high+bar.low)/2,basicUp=src-cfg.multiplier*atr,basicDn=src+cfg.multiplier*atr,up=committedUp!=null&&previousBar!=null&&previousBar.close>committedUp?Math.max(basicUp,committedUp):basicUp,dn=committedDn!=null&&previousBar!=null&&previousBar.close<committedDn?Math.min(basicDn,committedDn):basicDn;let trend=committedTrend;if(committedTrend===-1&&committedDn!=null&&bar.close>committedDn)trend=1;else if(committedTrend===1&&committedUp!=null&&bar.close<committedUp)trend=-1;return{trend:trend as 1|-1,value:trend===1?up:dn,up,dn};};const commitPartial=()=>{if(!partial)return;const result=candidate(partial),tr=trueRange(partial,previousBar);completedTrs.push(tr);if(cfg.useRmaAtr){if(committedAtr!=null)committedAtr=(committedAtr*(cfg.atrPeriod-1)+tr)/cfg.atrPeriod;else if(completedTrs.length>=cfg.atrPeriod)committedAtr=completedTrs.slice(-cfg.atrPeriod).reduce((a,b)=>a+b,0)/cfg.atrPeriod;}if(result){committedTrend=result.trend;committedUp=result.up;committedDn=result.dn;}previousBar=partial;};for(const candle of base){const nextBucket=Math.floor(candle.time/bucketSeconds)*bucketSeconds;if(bucket!=null&&nextBucket!==bucket)commitPartial();if(nextBucket!==bucket){bucket=nextBucket;partial={...candle,time:nextBucket};}else if(partial){partial.high=Math.max(partial.high,candle.high);partial.low=Math.min(partial.low,candle.low);partial.close=candle.close;}const result=partial?candidate(partial):null;if(result)rows.push({time:candle.time+60,trend:result.trend,value:result.value});}return rows;}

export function calculateController(entries:EntryRow[],exits:ExitRow[],trendRows:ChannelRow[],cfg:ControllerConfig):ControllerRow[]{if(!cfg.enabled)return[];const events=[...exits.map(row=>({time:row.time,priority:0,kind:"EXIT" as const,row})),...entries.filter(row=>row.entry!=="NONE").map(row=>({time:row.time,priority:1,kind:"ENTRY" as const,row}))].sort((a,b)=>a.time-b.time||a.priority-b.priority),output:ControllerRow[]=[];let state:ControllerState="FLAT",trendIndex=-1;for(const event of events){while(trendIndex+1<trendRows.length&&trendRows[trendIndex+1].time<=event.time)trendIndex++;const trend=trendIndex>=0?trendRows[trendIndex].trend:null;if(event.kind==="EXIT"){if(event.row.exit==="LONG"&&state==="LONG"){state="FLAT";output.push({time:event.time,action:"EXIT_LONG",state,reason:"EXIT_LAB_EXIT"});}else if(event.row.exit==="SHORT"&&state==="SHORT"){state="FLAT";output.push({time:event.time,action:"EXIT_SHORT",state,reason:"EXIT_LAB_EXIT"});}continue;}const direction=event.row.entry;if(direction==="NONE")continue;if(cfg.requireTrend&&((direction==="LONG"&&trend!==1)||(direction==="SHORT"&&trend!==-1)))continue;if(state===direction)continue;if(state==="FLAT"){state=direction;output.push({time:event.time,action:direction==="LONG"?"OPEN_LONG":"OPEN_SHORT",state,reason:"ENTRY"});continue;}if(cfg.allowFlip){state=direction;output.push({time:event.time,action:direction==="LONG"?"FLIP_LONG":"FLIP_SHORT",state,reason:"OPPOSITE_ENTRY"});}}return output;}
export function calculateBacktest(rows:ControllerRow[],base:Candle[]):BacktestStats{let side:"LONG"|"SHORT"|null=null,entryPrice=0,trades=0,wins=0,losses=0,grossProfit=0,grossLoss=0,candleIndex=0;const executionPrice=(time:number)=>{while(candleIndex<base.length&&base[candleIndex].time<time)candleIndex++;return candleIndex<base.length?base[candleIndex].open:null;},close=(price:number)=>{if(side==null)return;const pnl=side==="LONG"?price-entryPrice:entryPrice-price;trades++;if(pnl>0){wins++;grossProfit+=pnl;}else if(pnl<0){losses++;grossLoss+=-pnl;}side=null;};for(const row of rows){const price=executionPrice(row.time);if(price==null)continue;if(row.action==="EXIT_LONG"||row.action==="EXIT_SHORT"){close(price);continue;}if(row.action==="FLIP_LONG"||row.action==="FLIP_SHORT")close(price);if(row.action==="OPEN_LONG"||row.action==="FLIP_LONG"){side="LONG";entryPrice=price;}if(row.action==="OPEN_SHORT"||row.action==="FLIP_SHORT"){side="SHORT";entryPrice=price;}}return{trades,wins,losses,grossProfit,grossLoss,net:grossProfit-grossLoss,profitFactor:grossLoss>0?grossProfit/grossLoss:grossProfit>0?Infinity:null,winRate:trades>0?wins/trades*100:0};}
