import { useEffect,useMemo,useRef,useState,type CSSProperties } from "react";
import { CandlestickSeries,CrosshairMode,createChart,createSeriesMarkers,LineSeries,type IChartApi,type ISeriesApi,type Time } from "lightweight-charts";
import { useSharedMarket } from "./useSharedMarket";
import { chartBerlinTime } from "./berlinTime";
import { DEFAULT_ENTRY,DEFAULT_EXIT,DEFAULT_CHANNEL,DEFAULT_CONTROLLER,tfSeconds,type Candle,type EntryConfig,type ExitConfig,type ChannelConfig,type ControllerConfig,type EntryRow,type BacktestStats } from "./cockpitV2Core";

const BACKEND_BASE="https://qtrend-trading-engine.onrender.com";
const SYMBOLS=["GOLD","US100","US30","DE40","J225","UK100","US500","BTCUSD","ETHUSD","SILVER","OIL_CRUDE","CORN"];
const INTERVALS=["1m","2m","3m","5m","8m","10m","15m","18m","30m","1h"];
type ChartMode="candles"|"heikin";
type ModuleKey="view"|"entry"|"exit"|"channel"|"poc"|"controller";
type ExitModuleConfig=ExitConfig&{macdTf:string};
type InstrumentProfile={symbol:string;interval:string;chartMode:ChartMode;activeModule:ModuleKey;showPaneA:boolean;showPaneB:boolean;updatedAt:string;modules:{entry:EntryConfig;exit:ExitModuleConfig;channel:ChannelConfig;poc:Record<string,unknown>;controller:ControllerConfig}};
type TradingStatus={demo:boolean;execute_orders:boolean;config:{symbol:string;interval:string;size:number;auto_enabled:number}|null;event:{event_id:string;action:string;status:string;error?:string|null;created_at:string}|null};
type EngineSnapshot={version:number;symbol:string;generated_at:number;profile_id:number;profile:any;interval:string;base_candle_count:number;chart_candles:Candle[];entry_rows:any[];exit_rows:any[];channel_rows:any[];controller_rows:any[];exit_slow_line:any[];channel_line:any[];macd_points:{time:number;macd:number;signal:number}[];backtest:BacktestStats;latest_controller:any;trading:{auto_enabled:boolean;size:number}};

const profileKey=(symbol:string)=>`qtrend:cockpit-v2:profile:${symbol}`;
function defaultProfile(symbol:string,interval:string):InstrumentProfile{return{symbol,interval,chartMode:"candles",activeModule:"view",showPaneA:false,showPaneB:false,updatedAt:new Date().toISOString(),modules:{entry:{...DEFAULT_ENTRY},exit:{...DEFAULT_EXIT,exitOnTrendFlip:true,macdTf:"15m"},channel:{...DEFAULT_CHANNEL},poc:{},controller:{...DEFAULT_CONTROLLER}}};}
function readProfile(symbol:string,fallbackInterval:string):InstrumentProfile{try{const raw=localStorage.getItem(profileKey(symbol));if(!raw)return defaultProfile(symbol,fallbackInterval);const p=JSON.parse(raw),exit={...DEFAULT_EXIT,macdTf:"15m",...(p?.modules?.exit||{}),tf:"MTF",offset:0,useSlowExit:true} as ExitModuleConfig;return{...defaultProfile(symbol,fallbackInterval),...p,symbol,modules:{entry:{...DEFAULT_ENTRY,...(p?.modules?.entry||{})},exit,channel:{...DEFAULT_CHANNEL,...(p?.modules?.channel||{})},poc:{...(p?.modules?.poc||{})},controller:{...DEFAULT_CONTROLLER,...(p?.modules?.controller||{})}}};}catch{return defaultProfile(symbol,fallbackInterval);}}
function saveProfile(profile:InstrumentProfile){localStorage.setItem(profileKey(profile.symbol),JSON.stringify({...profile,updatedAt:new Date().toISOString()}));}
function heikin(c:Candle[]):Candle[]{if(!c.length)return[];const out:Candle[]=[];let po=(c[0].open+c[0].close)/2,pc=(c[0].open+c[0].high+c[0].low+c[0].close)/4;out.push({time:c[0].time,open:po,close:pc,high:Math.max(c[0].high,po,pc),low:Math.min(c[0].low,po,pc),volume:c[0].volume});for(let i=1;i<c.length;i++){const x=c[i],close=(x.open+x.high+x.low+x.close)/4,open=(po+pc)/2;out.push({time:x.time,open,close,high:Math.max(x.high,open,close),low:Math.min(x.low,open,close),volume:x.volume});po=open;pc=close;}return out;}
async function fetchJson(url:string,init:RequestInit={}){const r=await fetch(url,{cache:"no-store",...init}),text=await r.text();let j:any;try{j=JSON.parse(text);}catch{throw new Error(`Keine JSON-Antwort: ${text.slice(0,120)}`);}if(!r.ok||j?.ok===false)throw new Error(j?.info||j?.reason||j?.error||`HTTP ${r.status}`);return j;}
function phaseText(v:number){return v===1?"EXPANSION":v===2?"PULLBACK":v===3?"EXHAUSTION":"COMPRESSION";}
function dirText(v:number){return v===1?"UP":v===-1?"DOWN":"RANGE";}
const panel:CSSProperties={border:"1px solid #24324a",background:"#0b1220",borderRadius:10};
const inputStyle:CSSProperties={background:"#0a1020",border:"1px solid #334155",color:"#e5eefc",borderRadius:7,padding:"8px 10px",fontWeight:700};
const buttonStyle:CSSProperties={...inputStyle,cursor:"pointer"};
const emptyStats:BacktestStats={trades:0,wins:0,losses:0,grossProfit:0,grossLoss:0,net:0,profitFactor:null,winRate:0};

export default function CockpitV2(){
 const {symbol,interval,setSymbol,setInterval}=useSharedMarket();
 const [profile,setProfile]=useState<InstrumentProfile>(()=>readProfile(symbol,interval));
 const [snapshot,setSnapshot]=useState<EngineSnapshot|null>(null);
 const [selected,setSelected]=useState<Candle|null>(null);
 const [status,setStatus]=useState("Engine-Snapshot wird geladen …");
 const [busy,setBusy]=useState(false);
 const [tradingStatus,setTradingStatus]=useState<TradingStatus|null>(null);
 const [tradingMessage,setTradingMessage]=useState("SIGNALQUELLE ENGINE · Verbinden …");
 const priceHost=useRef<HTMLDivElement>(null),macdHost=useRef<HTMLDivElement>(null),chart=useRef<IChartApi|null>(null),macdChart=useRef<IChartApi|null>(null),series=useRef<ISeriesApi<"Candlestick">|null>(null),exitSlowSeries=useRef<ISeriesApi<"Line">|null>(null),channelTrendSeries=useRef<ISeriesApi<"Line">|null>(null),macdBlueSeries=useRef<ISeriesApi<"Line">|null>(null),macdRedSeries=useRef<ISeriesApi<"Line">|null>(null),markerApi=useRef<any>(null),candleMapRef=useRef(new Map<number,Candle>()),syncTimer=useRef<number|null>(null);
 const entryCfg=profile.modules.entry,exitCfg=profile.modules.exit,channelCfg=profile.modules.channel,controllerCfg=profile.modules.controller;
 const candles=snapshot?.chart_candles||[];
 const shown=useMemo(()=>profile.chartMode==="heikin"?heikin(candles):candles,[candles,profile.chartMode]);
 const entryRows=snapshot?.entry_rows||[],exitRows=snapshot?.exit_rows||[],channelRows=snapshot?.channel_rows||[],controllerRows=snapshot?.controller_rows||[];
 const exitSlowLine=snapshot?.exit_slow_line||[],channelLine=snapshot?.channel_line||[],macdPoints=snapshot?.macd_points||[];
 const backtestStats=snapshot?.backtest||emptyStats;
 const engineInterval=snapshot?.interval||interval;
 const entryByChartTime=useMemo(()=>{const map=new Map<number,EntryRow>(),sec=tfSeconds(engineInterval);for(const r of entryRows)map.set(Math.floor(Number(r.time)/sec)*sec,r);return map;},[entryRows,engineInterval]);
 const selectedEntry=selected?entryByChartTime.get(selected.time)||null:null;
 const selectedExit=selected?exitRows.find((r:any)=>Math.floor((Number(r.time)-1)/tfSeconds(engineInterval))*tfSeconds(engineInterval)===selected.time)||null:null;
 const selectedChannel=selected?[...channelRows].reverse().find((r:any)=>Number(r.time)<=selected.time+tfSeconds(engineInterval))||null:null;
 const selectedController=selected?[...controllerRows].reverse().find((r:any)=>Number(r.time)<=selected.time+tfSeconds(engineInterval))||null:null;

 async function refreshTradingStatus(){const j=await fetchJson(`${BACKEND_BASE}/cockpit-v2/trading-status?symbol=${encodeURIComponent(symbol)}&_ts=${Date.now()}`);setTradingStatus(j);return j as TradingStatus;}
 async function loadSnapshot(fit=false){try{setBusy(true);const j=await fetchJson(`${BACKEND_BASE}/cockpit-v2/snapshot?symbol=${encodeURIComponent(symbol)}&_ts=${Date.now()}`);const snap=j.snapshot as EngineSnapshot;setSnapshot(snap);setStatus(`${symbol} ${snap.interval} · ENGINE · ${snap.chart_candles?.length||0} Kerzen aus ${snap.base_candle_count||0}×1m · Profil ${snap.profile_id}`);if(!selected&&snap.chart_candles?.length)setSelected(snap.chart_candles[snap.chart_candles.length-1]);if(fit)queueMicrotask(()=>{chart.current?.timeScale().fitContent();macdChart.current?.timeScale().fitContent();});}catch(e){setStatus(`Snapshot: ${e instanceof Error?e.message:String(e)}`);}finally{setBusy(false);}}
 async function writeProfile(next:InstrumentProfile,showStatus=false){const saved={...next,interval:next.interval||interval,modules:{...next.modules,exit:{...next.modules.exit,tf:"MTF"}},updatedAt:new Date().toISOString()};saveProfile(saved);await fetchJson(`${BACKEND_BASE}/ui/strategy-event`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbol:`${symbol}__V2_PROFILE`,tf:saved.interval,side:"profile",time:Math.floor(Date.now()/1000),price:0,source:"cockpit_v2_profile",reason:JSON.stringify(saved)})});if(showStatus)setStatus(`Profil ${symbol} an EINZIGE Recheninstanz geschrieben`);setTradingMessage("SIGNALQUELLE ENGINE · Parameter synchronisiert");}
 function scheduleProfileWrite(next:InstrumentProfile){saveProfile(next);if(syncTimer.current)window.clearTimeout(syncTimer.current);syncTimer.current=window.setTimeout(()=>void writeProfile(next,false).catch(e=>setStatus(`Profilfehler: ${e instanceof Error?e.message:String(e)}`)),500);}
 function updateCalculatedProfile(mutator:(prev:InstrumentProfile)=>InstrumentProfile){setProfile(prev=>{const next=mutator(prev);scheduleProfileWrite(next);return next;});}
 async function persist(){try{await writeProfile(profile,true);}catch(e){setStatus(`Profilfehler: ${e instanceof Error?e.message:String(e)}`);}}
 async function changeTradingAuto(enabled:boolean){try{setTradingMessage(enabled?"AUTO wird eingeschaltet …":"AUTO wird ausgeschaltet …");await fetchJson(`${BACKEND_BASE}/cockpit-v2/auto`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbol,enabled})});await refreshTradingStatus();setTradingMessage(enabled?"AUTO ON":"AUTO OFF");}catch(e){setTradingMessage(`AUTO-Fehler: ${e instanceof Error?e.message:String(e)}`);}}
 async function runTradingTest(action:"LONG"|"SHORT"|"EXIT"){try{const size=Number(tradingStatus?.config?.size||0),eventId=`ui-test|${symbol}|${Date.now()}|${action}`,side=action==="LONG"?"long":action==="SHORT"?"short":"flat",command={event_id:eventId,symbol,interval:engineInterval,action,target_state:side,controller_action:`TEST_${action}`,controller_reason:"UI_TEST",event_time:Math.floor(Date.now()/1000),size,created_at:Date.now()};await fetchJson(`${BACKEND_BASE}/ui/strategy-event`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbol:"__V2_EXECUTION_QUEUE__",tf:engineInterval,side,time:command.event_time,price:0,source:"cockpit_v2_execution_queue",reason:JSON.stringify(command)})});setTradingMessage(`TEST ${action}: ${eventId}`);}catch(e){setTradingMessage(`Testfehler: ${e instanceof Error?e.message:String(e)}`);}}

 useEffect(()=>{candleMapRef.current=new Map(candles.map(c=>[Number(c.time),c]));},[candles]);
 useEffect(()=>{const next=readProfile(symbol,interval);setProfile(next);setSnapshot(null);setSelected(null);if(next.interval!==interval)setInterval(next.interval);void loadSnapshot(true);},[symbol]);
 useEffect(()=>{let stopped=false;const poll=async()=>{try{await Promise.all([loadSnapshot(false),refreshTradingStatus()]);if(!stopped)setTradingMessage("SIGNALQUELLE ENGINE · Bereit");}catch{} };void poll();const t=window.setInterval(()=>void poll(),3000);return()=>{stopped=true;window.clearInterval(t);};},[symbol]);
 useEffect(()=>()=>{if(syncTimer.current)window.clearTimeout(syncTimer.current);},[]);

 useEffect(()=>{if(!priceHost.current)return;const c=createChart(priceHost.current,{autoSize:true,layout:{background:{color:"#070b16"},textColor:"#dbe4ff"},grid:{vertLines:{color:"#172033"},horzLines:{color:"#172033"}},crosshair:{mode:CrosshairMode.Normal},rightPriceScale:{borderColor:"#334155",minimumWidth:78},timeScale:{borderColor:"#334155",timeVisible:true,secondsVisible:false,tickMarkFormatter:(t:any)=>chartBerlinTime(Number(t))},localization:{timeFormatter:(t:any)=>chartBerlinTime(Number(t))}});const s=c.addSeries(CandlestickSeries,{upColor:"#22c55e",downColor:"#ef4444",wickUpColor:"#22c55e",wickDownColor:"#ef4444",borderVisible:false});exitSlowSeries.current=c.addSeries(LineSeries,{color:"#f8fafc",lineWidth:2,priceLineVisible:false,lastValueVisible:false});channelTrendSeries.current=c.addSeries(LineSeries,{color:"#22c55e",lineWidth:3,priceLineVisible:false,lastValueVisible:false});chart.current=c;series.current=s;markerApi.current=createSeriesMarkers(s,[]);c.subscribeCrosshairMove(p=>{if(!p.time)return;const row=candleMapRef.current.get(Number(p.time));if(row)setSelected(row);});return()=>{c.remove();chart.current=null;series.current=null;markerApi.current=null;};},[]);
 useEffect(()=>{if(!macdHost.current)return;const c=createChart(macdHost.current,{autoSize:true,layout:{background:{color:"#070b16"},textColor:"#dbe4ff"},grid:{vertLines:{color:"#172033"},horzLines:{color:"#172033"}},rightPriceScale:{borderColor:"#334155",minimumWidth:78},timeScale:{borderColor:"#334155",timeVisible:true,secondsVisible:false,tickMarkFormatter:(t:any)=>chartBerlinTime(Number(t))},localization:{timeFormatter:(t:any)=>chartBerlinTime(Number(t))}});macdBlueSeries.current=c.addSeries(LineSeries,{color:"#2563eb",lineWidth:2,priceLineVisible:false,lastValueVisible:true});macdRedSeries.current=c.addSeries(LineSeries,{color:"#ef4444",lineWidth:2,priceLineVisible:false,lastValueVisible:true});macdChart.current=c;return()=>{c.remove();macdChart.current=null;macdBlueSeries.current=null;macdRedSeries.current=null;};},[]);
 useEffect(()=>{series.current?.setData(shown.map(c=>({time:c.time as Time,open:c.open,high:c.high,low:c.low,close:c.close})));},[shown]);
 useEffect(()=>{exitSlowSeries.current?.applyOptions({visible:exitCfg.enabled&&exitCfg.showLines});exitSlowSeries.current?.setData(exitSlowLine as any);},[exitSlowLine,exitCfg.enabled,exitCfg.showLines]);
 useEffect(()=>{channelTrendSeries.current?.applyOptions({visible:channelCfg.enabled&&channelCfg.showLines});channelTrendSeries.current?.setData((channelLine||[]).map((p:any)=>({time:Number(p.time) as Time,value:Number(p.value),color:Number(p.trend)===1?"#22c55e":"#ef4444"})) as any);},[channelLine,channelCfg.enabled,channelCfg.showLines]);
 useEffect(()=>{macdBlueSeries.current?.setData(macdPoints.map(p=>({time:p.time as Time,value:p.macd})));macdRedSeries.current?.setData(macdPoints.map(p=>({time:p.time as Time,value:p.signal})));macdChart.current?.timeScale().fitContent();},[macdPoints]);
 useEffect(()=>{if(!markerApi.current)return;const sec=tfSeconds(engineInterval),seen=new Set<string>(),chartTimes=new Set(candles.map(c=>Number(c.time))),markers:any[]=[];const valid=(t:number)=>chartTimes.has(t);if(entryCfg.enabled&&entryCfg.showMarkers)for(const r of entryRows){if(r.entry==="NONE")continue;const time=Math.floor(Number(r.time)/sec)*sec,key=`entry-${time}-${r.entry}`;if(!valid(time)||seen.has(key))continue;seen.add(key);markers.push({time:time as Time,position:r.entry==="LONG"?"belowBar":"aboveBar",color:r.entry==="LONG"?"#22c55e":"#ef4444",shape:r.entry==="LONG"?"arrowUp":"arrowDown",text:"",size:2});}if(exitCfg.enabled&&exitCfg.showMarkers)for(const r of exitRows){const time=Math.floor((Number(r.time)-1)/sec)*sec,key=`exit-${time}-${r.exit}`;if(!valid(time)||seen.has(key))continue;seen.add(key);markers.push({time:time as Time,position:r.exit==="LONG"?"aboveBar":"belowBar",color:r.exit==="LONG"?"#facc15":"#e879f9",shape:"square",text:"×",size:1.5});}if(controllerCfg.enabled&&controllerCfg.showMarkers)for(const r of controllerRows){const time=Math.floor((Number(r.time)-1)/sec)*sec;if(!valid(time))continue;const ol=r.action==="OPEN_LONG"||r.action==="FLIP_LONG",os=r.action==="OPEN_SHORT"||r.action==="FLIP_SHORT",el=r.action==="EXIT_LONG";markers.push({time:time as Time,position:ol?"belowBar":os?"aboveBar":el?"aboveBar":"belowBar",color:ol?"#38bdf8":os?"#fb923c":"#f8fafc",shape:ol?"arrowUp":os?"arrowDown":"circle",text:ol?(r.action==="FLIP_LONG"?"C FLIP L":"C LONG"):os?(r.action==="FLIP_SHORT"?"C FLIP S":"C SHORT"):el?"C EXIT L":"C EXIT S",size:2.5});}markerApi.current.setMarkers(markers.sort((a:any,b:any)=>Number(a.time)-Number(b.time)));},[candles,entryRows,exitRows,controllerRows,entryCfg.enabled,entryCfg.showMarkers,exitCfg.enabled,exitCfg.showMarkers,controllerCfg.enabled,controllerCfg.showMarkers,engineInterval]);

 const patchUiOnly=(p:Partial<InstrumentProfile>)=>setProfile(v=>{const next={...v,...p};saveProfile(next);return next;});
 const patchProfile=(p:Partial<InstrumentProfile>)=>updateCalculatedProfile(v=>({...v,...p}));
 const patchEntry=(p:Partial<EntryConfig>)=>updateCalculatedProfile(v=>({...v,modules:{...v.modules,entry:{...v.modules.entry,...p}}}));
 const patchExit=(p:Partial<ExitModuleConfig>)=>updateCalculatedProfile(v=>({...v,modules:{...v.modules,exit:{...v.modules.exit,...p,tf:"MTF"}}}));
 const patchChannel=(p:Partial<ChannelConfig>)=>updateCalculatedProfile(v=>({...v,modules:{...v.modules,channel:{...v.modules.channel,...p}}}));
 const patchController=(p:Partial<ControllerConfig>)=>updateCalculatedProfile(v=>({...v,modules:{...v.modules,controller:{...v.modules.controller,...p}}}));
 const changeInterval=(x:string)=>{setInterval(x);patchProfile({interval:x});};
 const tabs:ModuleKey[]=["view","entry","exit","channel","poc","controller"],active=profile.activeModule;

 return <div style={{height:"calc(100vh - 84px)",minHeight:720,display:"grid",gridTemplateRows:"auto 1fr",gap:10,padding:8,color:"#dbe4ff",background:"#050914"}}>
  <div style={{...panel,padding:10,display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><b style={{fontSize:16,color:"#67e8f9"}}>COCKPIT V2</b><select value={symbol} onChange={e=>setSymbol(e.target.value)} style={inputStyle}>{SYMBOLS.map(x=><option key={x}>{x}</option>)}</select><select value={interval} onChange={e=>changeInterval(e.target.value)} style={inputStyle}>{INTERVALS.map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>patchUiOnly({chartMode:profile.chartMode==="candles"?"heikin":"candles"})} style={buttonStyle}>{profile.chartMode==="heikin"?"HEIKIN":"KERZEN"}</button><button disabled={busy} onClick={()=>void loadSnapshot(true)} style={buttonStyle}>{busy?"LÄDT …":"AKTUALISIEREN"}</button><div style={{flex:1,minWidth:220,padding:"8px 12px",borderRadius:7,border:"1px solid #166534",background:"#052e1a",color:"#86efac",fontWeight:800}}>{status}</div><button onClick={()=>void persist()} style={{...buttonStyle,background:"#0f766e",color:"white"}}>PROFIL SPEICHERN</button></div>
  <div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) 380px",gap:10,minHeight:0}}>
   <div style={{display:"grid",gridTemplateRows:"minmax(360px,1fr) 190px",gap:8,minHeight:0}}>
    <div style={{...panel,overflow:"hidden",position:"relative"}}><div ref={priceHost} style={{position:"absolute",inset:0}}/><div style={{position:"absolute",top:10,left:12,zIndex:3,padding:"5px 8px",borderRadius:6,background:"#08111ecc",border:"1px solid #23324a",fontSize:12,fontWeight:800}}>{symbol} · ENGINE {engineInterval} · {profile.chartMode==="heikin"?"Heikin":"Candles"} · ENTRY {entryCfg.tf} · EXIT LAB 5/15/30/60 · MACD {exitCfg.macdTf} · TREND {channelCfg.tf}</div></div>
    <div style={{...panel,overflow:"hidden",position:"relative"}}><div ref={macdHost} style={{position:"absolute",inset:0}}/><div style={{position:"absolute",top:7,left:10,zIndex:3,padding:"4px 7px",borderRadius:5,background:"#08111ecc",border:"1px solid #23324a",fontSize:11,fontWeight:800}}>EXIT MACD · ENGINE {exitCfg.macdTf} · blau MACD / rot Signal</div></div>
   </div>
   <aside style={{display:"grid",gridTemplateRows:"minmax(0,3fr) minmax(0,2fr)",gap:10,minHeight:0,overflow:"hidden"}}><section style={{...panel,padding:12,overflow:"auto"}}><b>MODUL-EINSTELLUNGEN</b><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:5,margin:"10px 0 12px"}}>{tabs.map(k=><button key={k} onClick={()=>patchUiOnly({activeModule:k})} style={{...buttonStyle,padding:"7px 4px",fontSize:11,background:active===k?"#4c1d95":"#0a1020"}}>{k.toUpperCase()}</button>)}</div>{active==="view"&&<ViewSettings interval={interval} setInterval={changeInterval} profile={profile} patch={patchUiOnly}/>} {active==="entry"&&<EntrySettings cfg={entryCfg} patch={patchEntry}/>} {active==="exit"&&<ExitSettings cfg={exitCfg} patch={patchExit}/>} {active==="channel"&&<ChannelSettings cfg={channelCfg} patch={patchChannel}/>} {active==="controller"&&<ControllerSettings cfg={controllerCfg} patch={patchController} stats={backtestStats} trading={tradingStatus} tradingMessage={tradingMessage} onAuto={changeTradingAuto} onTest={runTradingTest}/>} {active==="poc"&&<div style={{color:"#64748b"}}>POC · Steckplatz vorbereitet.</div>}</section><section style={{...panel,padding:12,overflow:"auto"}}><b>INSPECTOR</b>{selected?<div style={{display:"grid",gap:7,marginTop:10}}><InfoRow k="Zeit" v={chartBerlinTime(selected.time)}/><InfoRow k="Open" v={selected.open}/><InfoRow k="High" v={selected.high}/><InfoRow k="Low" v={selected.low}/><InfoRow k="Close" v={selected.close}/><InfoRow k="ENTRY" v={selectedEntry?.entry||"NONE"}/><InfoRow k="DIR / PHASE" v={selectedEntry?`${dirText(selectedEntry.dir)} / ${phaseText(selectedEntry.phase)}`:"—"}/><InfoRow k="EXIT" v={selectedExit?.exit||"NONE"}/><InfoRow k="EXIT GRUND" v={selectedExit?.reason||"—"}/><InfoRow k="CHANNEL" v={selectedChannel?(selectedChannel.trend===1?"LONG":"SHORT"):"—"}/><InfoRow k="CONTROLLER" v={selectedController?.state||"FLAT"}/><InfoRow k="LIVE QUELLE" v="EINE ENGINE-BERECHNUNG"/></div>:null}</section></aside>
  </div>
 </div>;
}

function ViewSettings({interval,setInterval,profile,patch}:{interval:string;setInterval:(x:string)=>void;profile:InstrumentProfile;patch:(p:Partial<InstrumentProfile>)=>void}){return <div style={{display:"grid",gap:10}}><label>Chart-TF <select value={interval} onChange={e=>setInterval(e.target.value)} style={inputStyle}>{INTERVALS.map(x=><option key={x}>{x}</option>)}</select></label><label>Pane A <input type="checkbox" checked={profile.showPaneA} onChange={e=>patch({showPaneA:e.target.checked})}/></label><label>Pane B <input type="checkbox" checked={profile.showPaneB} onChange={e=>patch({showPaneB:e.target.checked})}/></label></div>}
function EntrySettings({cfg,patch}:{cfg:EntryConfig;patch:(p:Partial<EntryConfig>)=>void}){const num=(k:keyof EntryConfig,l:string,s=1)=><label style={{display:"grid",gap:4}}>{l}<input type="number" step={s} value={Number(cfg[k])} onChange={e=>patch({[k]:Number(e.target.value)} as Partial<EntryConfig>)} style={inputStyle}/></label>;return <div style={{display:"grid",gap:10}}><label>ENTRY TF <select value={cfg.tf} onChange={e=>patch({tf:e.target.value})} style={inputStyle}>{INTERVALS.map(x=><option key={x}>{x}</option>)}</select></label><label>Modul aktiv <input type="checkbox" checked={cfg.enabled} onChange={e=>patch({enabled:e.target.checked})}/></label><label>ENTRY Marker <input type="checkbox" checked={cfg.showMarkers} onChange={e=>patch({showMarkers:e.target.checked})}/></label><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{num("fastSma","Fast SMA")}{num("slowSma","Slow SMA")}{num("atrLen","ATR Länge")}{num("rsiLen","RSI Länge")}{num("macdFast","MACD Fast")}{num("macdSlow","MACD Slow")}{num("macdSignal","MACD Signal")}{num("expansionMomentum","Momentum min")}{num("expansionEnergy","Energy min")}{num("expansionVolatility","Volatility min")}{num("expansionCompressionMax","Compression max")}{num("compressionMin","Compression min")}{num("phaseSwitchMargin","Phase Margin",.5)}</div></div>}
function ExitSettings({cfg,patch}:{cfg:ExitModuleConfig;patch:(p:Partial<ExitModuleConfig>)=>void}){const num=(k:keyof ExitModuleConfig,l:string)=><label style={{display:"grid",gap:4}}>{l}<input type="number" value={Number(cfg[k])} onChange={e=>patch({[k]:Number(e.target.value)} as Partial<ExitModuleConfig>)} style={inputStyle}/></label>;return <div style={{display:"grid",gap:10}}><div style={{padding:9,border:"1px solid #334155",borderRadius:8,fontWeight:900,color:"#f8fafc"}}>QTrend EXIT LAB V1 · feste TF: 5m + 15m + 30m + 1h</div><label>Modul aktiv <input type="checkbox" checked={cfg.enabled} onChange={e=>patch({enabled:e.target.checked})}/></label><label>EXIT Marker anzeigen <input type="checkbox" checked={cfg.showMarkers} onChange={e=>patch({showMarkers:e.target.checked})}/></label><label>SMA Slow anzeigen <input type="checkbox" checked={cfg.showLines} onChange={e=>patch({showLines:e.target.checked})}/></label><label>EXIT bei Trendwechsel <input type="checkbox" checked={cfg.exitOnTrendFlip} onChange={e=>patch({exitOnTrendFlip:e.target.checked})}/></label><label style={{display:"grid",gap:4}}>MACD TF<select value={cfg.macdTf} onChange={e=>patch({macdTf:e.target.value})} style={inputStyle}>{INTERVALS.map(x=><option key={x}>{x}</option>)}</select></label><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{num("fastSma","Fast SMA")}{num("slowSma","Slow SMA")}{num("atrLen","ATR Länge")}{num("rsiLen","RSI Länge")}{num("macdFast","MACD Fast")}{num("macdSlow","MACD Slow")}{num("macdSignal","MACD Signal")}</div><div style={{fontSize:11,color:"#94a3b8"}}>Zusatzregel MACD: blau kreuzt rot von unten → SHORT EXIT. Blau kreuzt rot von oben → LONG EXIT. Berechnung ausschließlich in der Engine.</div></div>}
function ChannelSettings({cfg,patch}:{cfg:ChannelConfig;patch:(p:Partial<ChannelConfig>)=>void}){const num=(k:keyof ChannelConfig,l:string,s=1)=><label style={{display:"grid",gap:4}}>{l}<input type="number" step={s} value={Number(cfg[k])} onChange={e=>patch({[k]:Number(e.target.value)} as Partial<ChannelConfig>)} style={inputStyle}/></label>;return <div style={{display:"grid",gap:10}}><label>TREND TF <select value={cfg.tf} onChange={e=>patch({tf:e.target.value})} style={inputStyle}>{INTERVALS.map(x=><option key={x}>{x}</option>)}</select></label><label>Modul aktiv <input type="checkbox" checked={cfg.enabled} onChange={e=>patch({enabled:e.target.checked})}/></label><label>Trendlinie <input type="checkbox" checked={cfg.showLines} onChange={e=>patch({showLines:e.target.checked})}/></label><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{num("atrPeriod","ATR Periode")}{num("multiplier","Multiplikator",.1)}</div><label>Wilder ATR <input type="checkbox" checked={cfg.useRmaAtr} onChange={e=>patch({useRmaAtr:e.target.checked})}/></label></div>}
function ControllerSettings({cfg,patch,stats,trading,tradingMessage,onAuto,onTest}:{cfg:ControllerConfig;patch:(p:Partial<ControllerConfig>)=>void;stats:BacktestStats;trading:TradingStatus|null;tradingMessage:string;onAuto:(x:boolean)=>void;onTest:(x:"LONG"|"SHORT"|"EXIT")=>void}){return <div style={{display:"grid",gap:10}}><label>Controller aktiv <input type="checkbox" checked={cfg.enabled} onChange={e=>patch({enabled:e.target.checked})}/></label><label>Controller-Marker <input type="checkbox" checked={cfg.showMarkers} onChange={e=>patch({showMarkers:e.target.checked})}/></label><label>Trendrichtung verlangen <input type="checkbox" checked={cfg.requireTrend} onChange={e=>patch({requireTrend:e.target.checked})}/></label><label>Direkten Flip erlauben <input type="checkbox" checked={cfg.allowFlip} onChange={e=>patch({allowFlip:e.target.checked})}/></label><div style={{padding:9,border:"1px solid #0f766e",borderRadius:8,color:"#5eead4",fontWeight:900}}>LIVE-SIGNALQUELLE: EINE ENGINE-BERECHNUNG</div><InfoRow k="PF" v={stats.profitFactor==null?"—":stats.profitFactor.toFixed(3)}/><InfoRow k="Trades" v={stats.trades}/><InfoRow k="AUTO" v={trading?.config?.auto_enabled?"ON":"OFF"}/><InfoRow k="Positionsgröße" v={trading?.config?.size??"—"}/><InfoRow k="Queue" v={trading?.event?.status||"—"}/><div style={{fontSize:11,color:"#86efac"}}>{tradingMessage}</div><button onClick={()=>onAuto(!Boolean(trading?.config?.auto_enabled))} style={{...buttonStyle,background:trading?.config?.auto_enabled?"#7f1d1d":"#166534",color:"white"}}>{trading?.config?.auto_enabled?"AUTO AUSSCHALTEN":"AUTO EINSCHALTEN"}</button><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:6}}><button onClick={()=>onTest("LONG")} style={buttonStyle}>TEST LONG</button><button onClick={()=>onTest("SHORT")} style={buttonStyle}>TEST SHORT</button><button onClick={()=>onTest("EXIT")} style={buttonStyle}>TEST EXIT</button></div></div>}
function InfoRow({k,v}:{k:string;v:any}){return <div style={{display:"grid",gridTemplateColumns:"112px 1fr",gap:8,paddingBottom:6,borderBottom:"1px solid #182236"}}><span style={{color:"#67e8f9",fontWeight:800}}>{k}</span><span style={{textAlign:"right",color:"#f8fafc",fontWeight:800}}>{typeof v==="number"?Number(v).toFixed(3):String(v)}</span></div>}
